# See https://github.com/lowlighter/metrics for documentation
# This worflow is scheduled for every hour, and also run after each commit (GitHub action excluded) on master/main branch

name: Metrics
on:
  schedule:
    - cron: "0 0-22/2 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
          
      - name: 🦑 Personal metrics (anilist)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.personal.anilist.svg
          token: NOT_NEEDED
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, characters, watching
          plugin_anilist_limit: 8
          plugin_anilist_shuffle: yes
          plugin_anilist_limit_characters: 22
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          plugin_anilist_user: slashiy
          
